keywords:
  - computer vision # add key words here...
  - africa
  - malaria

endpoint_url: https://query.wikidata.org/sparql


### example config ### 

keywords_example: 
  - africa  
  - machine learning 
  - pathology 
  
endpoint_url_example: https://query.wikidata.org/sparql